export {default as Icon} from './Icon/Icon'
export {default as Layout} from './Layout/Layout'
export {default as Logo} from './Logo/Logo'
export {default as Promobar} from './Promobar/Promobar'
export {default as Searchbar} from './Searchbar/Searchbar'
export {default as VideoList} from './VideoList/VideoList'
export {default as VideoListItem} from './VideoList/VideoListItem'
//export {default as VideoPlayer} from './VideoPlayer/VideoPlayer'